### ISSUE TITLE
Phonegap Build fails to build Android

### ISSUE THREAD

**Issue by fosron** [fechanique/cordova-plugin-fcm#232]
Trying to build this app for Android on Phonegap build. iOS went through, Android throws the same old error

Version: `<plugin name="cordova-plugin-fcm" spec="~2.1.1" />`

I've put the file `google-services.json` in both root `/google-services.json` and `/project/google-services.json`.

Screenshot of file tree: 
![screenshot 2017-01-26 18 53 33](https://cloud.githubusercontent.com/assets/3708631/22341282/efbf1daa-e3f8-11e6-94bc-7645ee715c01.png)

I'm glad that iOS goes through, no need to use a private repo and the other config plugin, but still, that's a problem.

Stack trace from Phonegap build:

```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /project/src/debug/google-services.json
  /project/google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.042 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /project/src/debug/google-services.json
  /project/google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)```

**Comment by BlitZz96** [comment]
You probably forgot to update and or install the [right android SDK tools](http://stackoverflow.com/questions/37310188/failed-to-resolve-com-google-firebasefirebase-core9-0-0).

**Comment by fosron** [comment]
http://build.phonegap.com/ - this is the service i use for this purpose.

**Comment by BlitZz96** [comment]
Did a fast google search and found this: [Phonegap Build Firebase](http://stackoverflow.com/a/39756068/3058905). Hope it helps.
I'd recommend in the future to just build your apps with the CLI instead. This way you will have more control.

**Comment by fosron** [comment]
I've clearly done my share of research before coming here. https://github.com/stetro/cordova-plugin-fcm-config clearly states ```!! This Plugin is not necessary if cordova-plugin-fcm > 2.0 is used !!```. I've used the previously stated plugin, but it's not viable in production. Thanks for the advice, but using this is service is better for me & my team.

**Comment by ahmedmohyeldean** [comment]
from 4 days ago I'm looking for a solution to turn on notifications .. continued to something and did not get the solution .. plz tell me if you reach to it ..

**Comment by sparklton** [comment]
iOS builds are passing with PhoneGap, but the application crashes on device because ipa contains malformed GoogleService-Info.plist. The Android builds don't even pass because it is impossible to transfer the google service file to PG. This plugin doesn't work with popular cloud build services like PG or IntelXDK because it uses odd way to integrate service files. If anyone knows a working fork addressing these issues, please share.

**Comment by jtreanor** [comment]
Just to add a little more context here: this is failing because Phonegap Build does not support hooks. See a recent discussion [here](https://forums.adobe.com/message/9318835#9318835).

**Comment by SkateFreak** [comment]
@jtreanor does it mean i can not build with PhoneGap Build an app that uses ```cordova-plugin-fcm```?
