### ISSUE TITLE
buildToolsVersion is not specified.

### ISSUE THREAD

**Issue by asifahmed11** [fechanique/cordova-plugin-fcm#234]
Hi,

After adding to the plugin to my project , i'm getting the following error.

`Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalStateException: buildToolsVersion is not specified.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:645)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:608)
        at com.android.build.gradle.BasePlugin$10.call(BasePlugin.java:605)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:120)
        at com.android.build.gradle.BasePlugin.lambda$createTasks$1(BasePlugin.java:603)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:93)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:82)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy12.afterEvaluate(Unknown Source)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:67)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:61)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:540)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:93)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:124)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:121)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)

BUILD FAILED

Total time: 3.768 secs
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

FAILURE: Build failed with an exception.

* Where:
Script 'D:\Asif\ClientVisitApp\platforms\android\cordova-plugin-fcm\clientvisitmanagement-FCMPlugin.gradle' line: 13

* What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'com' for root project 'android' of type org.gradle.api.Project.
`

Is there a problem in my project?

**Comment by zaideygrek** [comment]
Hello, I have the same problem, have you found a solution ? Thanks !

**Comment by haajira** [comment]
Remove the platform and add it back..
Cordova platform remove android
Cordova platform add android

**Comment by andrewoodleyjr** [comment]
+1 Doesnt work.

**Comment by mahieddine-ichir** [comment]
nope ... does not work neither :-( 👍

**Comment by davidhooey** [comment]
Didn't work for me either. Removed `6.2.2` and added `6.2.3` with no luck.

**Comment by DharmendraVaishnav91** [comment]
+1  i am facing the same issue.

**Comment by Virendrabaskar** [comment]
For me it got fixed by adding  attribute `android-versionCode="<int>" ` to widget tag in `config.xml` .
I got `buildToolsVersion is not specified`  error when I use `android-versionCode="<String>" `

**Note** : I am using  cordova **6.5.0**

**Comment by jcastillohand** [comment]
hello, I have the same problem =(
`
> cordova run android
ANDROID_HOME=/Users/jaircastillo/Documents/android-sdk-macosx
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
Subproject Path: CordovaLib
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.

	at build_c2tgg73jga1lwl97hdrdn2gvw.run(/Users/jaircastillo/Documents/ionic Apps/prueba/platforms/android/build.gradle:137)
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.

java.lang.IllegalStateException: buildToolsVersion is not specified.

..................

* Where:
Build file '/Users/jaircastillo/Documents/ionic Apps/prueba/platforms/android/build.gradle' line: 180

* What went wrong:
A problem occurred evaluating root project 'android'.
> Invalid revision: 26.0.0.2`

**Comment by jcastillohand** [comment]
Hello, I have the same problem =(

**Comment by denzelwamburu** [comment]
Having same issue on `cordova@6.2.2`

**Comment by matejkramny** [comment]
having the same issue, this seems to be the cause for me. Could be some version misalignment between plugins that require google services.

```
FAILURE: Build failed with an exception.

* Where:
Script '/Users/m/p/app/platforms/android/cordova-plugin-fcm/app-FCMPlugin.gradle' line: 13

* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"
```

Any ideas?

**Comment by matejkramny** [comment]
nvm, there's a better plugin that actually works. Not to mention this repository has poor codebase.

https://www.npmjs.com/package/cordova-plugin-firebase

**Comment by navneetnivu07** [comment]
Same problem here also. If someone found the solution, please comment.

**Comment by sijakret** [comment]
same problem here.
tried setting the ANDROID_HOME env variable; did not help :(

@matejkramny 
https://www.npmjs.com/package/cordova-plugin-firebase
has exactly the same problem, if id add either of them (cordova-plugin-firebase or this one: cordova-plugin-fcm) with

`cordova plugin add ...`

i get the error mentioned in this issue.
as soon as i remove them with

`cordova plugin remove ...`

everything is back to normal.
To me this seems to indicate that there is a problem with a dependency or framework the two are both using. I have next to no experience with cordova/android though..

**Comment by sijakret** [comment]
here's what fixed it for me:

open android studio.
go to:
configure -> sdk manager -> Appearance & Behavior -> System Settings -> Android SDK -> SDK Tools 

.. and make sure you have these installed and up to date:
* Android SDK Build tools
* Google Play Services
* Google Repository

**Comment by russcarver** [comment]
I tried all the above, but it was @Virendrabaskar comment that did it for me.  Use `android-versionCode="1"`

**Comment by rodneymanao** [comment]
Pessoal, depois de tentar muitas alternativas, simplesmente o que funcionou foi a mudança do caminho do sdk, conforme citado pelo colega @navneetnivu07.

**Comment by psjsaravana** [comment]
Updating Google Play Services and adding android-versionCode="1" resolved my issue, thanks @Virendrabaskar  @sijakret

**Comment by erlangshen312** [comment]
Hi,
We detected issue BuildToolVersion. 

We updated all things by sdkManager and change anything but unSuccessful. 
After searching problem we find error in simple part. in **config.xml** change android-versionCode="2000**XX**" id="*" version="2.0.3".
Where is XX change to 30 or 40 etc ... like this, if u will write 23 they isn't working and give error like BuildToolVersion. 

Sorry for my english.

**Comment by sdanieljose** [comment]
Hi! I'm trying to resolve this issue, after many attempts, i solved like this:

1) Remove android / Add android:
cordova platform rm android
cordova platform add android

2) Check the environment variables and path of sdk

3) Install the plugin
cordova plugin add cordova-plugin-fcm

4) Check build.graddle file (project folder / platforms / build.graddle) - **This Saved My Life**
When you download the file google-services.json he asks to change the file and add the line in dependencies:

**dependencies {
        another classpaths
        ...
        classpath 'com.google.gms:google-services:4.0.1'
}**

Note: Add the line without **comma** and please check the version in Firebase Console when download google-services.json

5) Build project
cordova build android

I hope it helps! Enjoy

**Comment by jebazerosoft** [comment]
Hi
I have solved it by verifying the packages in Android SDK Manager as Administrator. 
Try to check the SDK tools needs any updates. Hope it helps
