### ISSUE TITLE
[Android] Key google.sent_time expected String but value was a java.lang.Long

### ISSUE THREAD

**Issue by davideas** [fechanique/cordova-plugin-fcm#253]
The error appears in the cycle `for` at FCMPluginActivity.java:36
```
Key google.sent_time expected String but value was a java.lang.Long.  The default value <null> was returned.
W/Bundle: Attempt to cast generated internal exception:
lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
android.os.BaseBundle.getString(BaseBundle.java:921)
at com.gae.scaffolder.plugin.FCMPluginActivity.onCreate(FCMPluginActivity.java:36)
at android.app.Activity.performCreate(Activity.java:6221)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2611)
...
D/FCMPlugin: 	Key: google.sent_time Value: null
D/FCMPlugin: 	Key: key1 Value: value1
D/FCMPlugin: 	Key: body Value: Body1
D/FCMPlugin: 	Key: from Value: 1053396333817
D/FCMPlugin: 	Key: title Value: Title1
D/FCMPlugin: 	Key: google.message_id Value: 0:1487084036831624%f4339ff6f4339ff6
D/FCMPlugin: 	Key: collapse_key Value: ...
```

**Comment by edgargrs** [comment]
Have you solved this problem?
