### ISSUE TITLE
EXACT SOLUTION FOR BUILD ISSUE PLEASE !!!! Build becomes successfull but App crashes

### ISSUE THREAD

**Issue by rehanhanar7** [fechanique/cordova-plugin-fcm#311]
Hi may I know what is the exact fix ??

**Below is my project.properties file**

target=android-23
android.library.reference.1=CordovaLib
cordova.gradle.include.1=cordova-plugin-badge/usc-badge.gradle
cordova.system.library.1=com.android.support:support-v4:+
cordova.system.library.2=com.google.firebase:firebase-core:+
cordova.system.library.3=com.google.firebase:firebase-messaging:+
cordova.gradle.include.2=cordova-plugin-fcm/usc-FCMPlugin.gradle
cordova.system.library.4=com.squareup.okhttp3:okhttp:3+

**The below is the dependancy in Build.gradle file of PROJECT_NAME/platforms/android/build.gradle file**

dependencies {
classpath 'com.android.tools.build:gradle:1.5.0'
}

**Below is the issue i get :**

What went wrong:
Execution failed for task ':processDebugGoogleServices'.
Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.0.0.

**Can anyone tell me what is exact fix ???**

**After reading the OTHER build issues post #306 and #310  posts I did the following change in project.properties file. Build becomes successful but the App crashes**.

target=android-23
android.library.reference.1=CordovaLib
cordova.gradle.include.1=cordova-plugin-badge/usc-badge.gradle
cordova.system.library.1=com.android.support:support-v4:+
cordova.system.library.2=com.google.firebase:firebase-core:9.0.0
cordova.system.library.3=com.google.firebase:firebase-messaging:9.0.0
cordova.gradle.include.2=cordova-plugin-fcm/usc-FCMPlugin.gradle
cordova.system.library.4=com.squareup.okhttp3:okhttp:3+

Can anyone tell me what to do in the above config file to fix the build issue and that app should run without crash.

**Comment by rehanhanar7** [comment]
**When i Debug in Android Studio I get the following error**

05-19 13:31:55.601 3769-5055/? E/ActivityManager: applyOptionsLocked: pendingOptions.getStartX()=359pendingOptions.getStartY()=592
05-19 13:31:55.625 32409-32409/? E/Zygote: v2
05-19 13:31:55.627 32409-32409/? E/Zygote: accessInfo : 0
05-19 13:31:55.797 32409-32409/com.uslbm.usc E/FirebaseApp: Firebase API initialization failure.
                                                            java.lang.reflect.InvocationTargetException
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.google.firebase.FirebaseApp.zza(Unknown Source)
                                                                at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                                                                at com.google.firebase.FirebaseApp.zzbu(Unknown Source)
                                                                at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                                                                at android.content.ContentProvider.attachInfo(ContentProvider.java:1758)
                                                                at android.content.ContentProvider.attachInfo(ContentProvider.java:1733)
                                                                at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                at android.app.ActivityThread.installProvider(ActivityThread.java:6335)
                                                                at android.app.ActivityThread.installContentProviders(ActivityThread.java:5927)
                                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5866)
                                                                at android.app.ActivityThread.-wrap3(ActivityThread.java)
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                at android.os.Looper.loop(Looper.java:154)
                                                                at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                             Caused by: java.lang.IllegalAccessError: Method 'void android.support.v4.content.ContextCompat.<init>()' is inaccessible to class 'com.google.firebase.iid.zzg' (declaration of 'com.google.firebase.iid.zzg' appears in /data/app/com.uslbm.usc-2/base.apk)
                                                                at com.google.firebase.iid.zzg.zzeC(Unknown Source)
                                                                at com.google.firebase.iid.zzg.<init>(Unknown Source)
                                                                at com.google.firebase.iid.zzg.<init>(Unknown Source)
                                                                at com.google.firebase.iid.zzd.zzb(Unknown Source)
                                                                at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                at com.google.firebase.FirebaseApp.zza(Unknown Source) 
                                                                at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                at com.google.firebase.FirebaseApp.initializeApp(Unknown Source) 
                                                                at com.google.firebase.FirebaseApp.zzbu(Unknown Source) 
                                                                at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source) 
                                                                at android.content.ContentProvider.attachInfo(ContentProvider.java:1758) 
                                                                at android.content.ContentProvider.attachInfo(ContentProvider.java:1733) 
                                                                at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source) 
                                                                at android.app.ActivityThread.installProvider(ActivityThread.java:6335) 
                                                                at android.app.ActivityThread.installContentProviders(ActivityThread.java:5927) 
                                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5866) 
                                                                at android.app.ActivityThread.-wrap3(ActivityThread.java) 
                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703) 
                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                at android.os.Looper.loop(Looper.java:154) 
                                                                at android.app.ActivityThread.main(ActivityThread.java:6692) 
                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
05-19 13:31:56.200 32409-32428/com.uslbm.usc E/FA: Task exception on worker thread: java.lang.IllegalAccessError: Method 'void android.support.v4.content.ContextCompat.<init>()' is inaccessible to class 'com.google.firebase.iid.zzg' (declaration of 'com.google.firebase.iid.zzg' appears in /data/app/com.uslbm.usc-2/base.apk): com.google.android.gms.measurement.internal.zzt.zzEd(Unknown Source)
05-19 13:31:56.680 32409-32409/com.uslbm.usc E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.uslbm.usc, PID: 32409
                                                               java.lang.IllegalAccessError: Method 'void android.support.v4.content.ContextCompat.<init>()' is inaccessible to class 'com.google.firebase.iid.zzg' (declaration of 'com.google.firebase.iid.zzg' appears in /data/app/com.uslbm.usc-2/base.apk)
                                                                   at com.google.firebase.iid.zzg.zzeC(Unknown Source)
                                                                   at com.google.firebase.iid.zzg.<init>(Unknown Source)
                                                                   at com.google.firebase.iid.zzg.<init>(Unknown Source)
                                                                   at com.google.firebase.iid.zzd.zzb(Unknown Source)
                                                                   at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
                                                                   at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
                                                                   at com.google.firebase.messaging.FirebaseMessaging.getInstance(Unknown Source)
                                                                   at com.gae.scaffolder.plugin.FCMPlugin.initialize(FCMPlugin.java:36)
                                                                   at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
                                                                   at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:172)
                                                                   at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:98)
                                                                   at org.apache.cordova.PluginManager.init(PluginManager.java:87)
                                                                   at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:116)
                                                                   at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:144)
                                                                   at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:214)
                                                                   at com.uslbm.usc.MainActivity.onRequestPermissionsResult(MainActivity.java:93)
                                                                   at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7404)
                                                                   at android.app.Activity.dispatchActivityResult(Activity.java:7230)
                                                                   at android.app.ActivityThread.deliverResults(ActivityThread.java:4477)
                                                                   at android.app.ActivityThread.handleSendResult(ActivityThread.java:4524)
                                                                   at android.app.ActivityThread.-wrap22(ActivityThread.java)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                   at

**Comment by rehanhanar7** [comment]
Temporary solution : 

@lp1bp Thanks Man !!!

1. Remove the existing FCM plugin
2. Add the plugin with this command "cordova plugin add https://github.com/lp1bp/cordova-plugin-fcm"
