### ISSUE TITLE
Deploy to device fail

### ISSUE THREAD

**Issue by cirovargas** [fechanique/cordova-plugin-fcm#361]
Hi, 

Im using ionic and trying to deploy to android device but the build fails, seeking other issues sugestions i changed the '+' to '9.0.0' in the project.properties file and the deploy go ok but the app dont load with the fatal error:

> 07-30 05:29:51.133 4905-4905/MYAPPID E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                      Process: com.prontorush.driver, PID: 4905
>                                                                      java.lang.IllegalAccessError: Method 'void android.support.v4.content.ContextCompat.<init>()' is inaccessible to class 'com.google.firebase.iid.zzg' (declaration of 'com.google.firebase.iid.zzg' appears in /data/app/MYAPP-2/split_lib_dependencies_apk.apk:classes19.dex)
>                                                                          at com.google.firebase.iid.zzg.zzeC(Unknown Source)
>                                                                          at com.google.firebase.iid.zzg.<init>(Unknown Source)
>                                                                          at com.google.firebase.iid.zzg.<init>(Unknown Source)
>                                                                          at com.google.firebase.iid.zzd.zzb(Unknown Source)
>                                                                          at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
>                                                                          at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
>                                                                          at com.google.firebase.messaging.FirebaseMessaging.getInstance(Unknown Source)
>                                                                          at com.gae.scaffolder.plugin.FCMPlugin.initialize(FCMPlugin.java:36)
>                                                                          at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:57)
>                                                                          at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
>                                                                          at org.apache.cordova.PluginManager.startupPlugins(PluginManager.java:97)
>                                                                          at org.apache.cordova.PluginManager.init(PluginManager.java:86)
>                                                                          at org.apache.cordova.CordovaWebViewImpl.init(CordovaWebViewImpl.java:115)
>                                                                          at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:149)
>                                                                          at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:224)
>                                                                          at com.prontorush.driver.MainActivity.onCreate(MainActivity.java:39)
>                                                                          at android.app.Activity.performCreate(Activity.java:6942)
>                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
>                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
>                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
>                                                                          at android.app.ActivityThread.-wrap14(ActivityThread.java)
>                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
>                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                          at android.os.Looper.loop(Looper.java:154)
>                                                                          at android.app.ActivityThread.main(ActivityThread.java:6682)
>                                                                          at java.lang.reflect.Method.invoke(Native Method)
>                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
>                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

if i update to a superior version  > 9.0.0 the build fails with the error:

`Found com.google.android.gms:play-services-location:11.0.4, but version 9.0.0 is needed for the google-services plugin.`

**Comment by maxime3002** [comment]
not compatible with cordova-plugin-analytics or cordova-plugin-push
