### ISSUE TITLE
Code is working until upload to phonegap

### ISSUE THREAD

**Issue by ghost** [fechanique/cordova-plugin-fcm#454]
Hi guys,

I'm trying to include cordova-plugin-fcm into my cordova app. Everything works so far and the Android build was successful. The moment I upload onto Phonegap the following message appears:

```
:processDebugGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /project/src/debug/google-services.json
  /project/google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.32 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /project/src/debug/google-services.json
  /project/google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

```

**Comment by ghost** [comment]
I also added this one as per Stackoverflow/GitHub but still the same error

`<platform name="android">
  <resource-file src="google-services.json" target="app/google-services.json" />
</platform>`

**Comment by jonfreynik** [comment]
I am working to get my environment up and running and I just worked through this same error. The compilation is failing because it looks to be looking for the google-services.json file and it cannot find it.

    File google-services.json is missing. The Google Services Plugin cannot function without it. 
    Searched Location: 
    /project/src/debug/google-services.json
    /project/google-services.json

So if you move that file to either of the two locations:

    /project/src/debug/google-services.json
    /project/google-services.json

the compilation process should continue.

-- Editing my comment as I am now experiencing the same issue - I was able to get the build running locally on my machine by moving the file to the above locations but the build still fails on Adobe Phone Gap Build. - if I am able to get this working I will respond again.

**Comment by jonfreynik** [comment]
@mad2kx - I was able to get the build process for Android to finish in Adobe Phone Gap Build - by adding the following line to my config.xml file inside the < widget > element.

    <preference name="phonegap-version" value="cli-7.1.0" />

Also needed is to put the google-services.json file in the root of the application and include the following < resource-file > element in the config.xml file.

    <platform name="android">
        <resource-file src="google-services.json" target="google-services.json" />
        ....
    </platform>

The < preference > element is what fixed it for me.

Let me know if that works for you as well.
