### ISSUE TITLE
Execution failed for task ':processDebugResources'.

### ISSUE THREAD

**Issue by wisesolution0502** [fechanique/cordova-plugin-fcm#597]
We have been using it well until last week.
But today occured cordova android build error.
--[*log*]------------------------------------------
ANDROID_HOME=C:\Users\devbear\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_191
Subproject Path: CordovaLib
Starting a Gradle Daemon (subsequent builds will be faster)
google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 9.0.0 will be used.
please apply google-services plugin at the bottom of the build file.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_8rbo1v30mfd7ki4o3c6jr2iel.run(D:\cordova\fdk_storyway_app_fran\platforms\android\build.gradle:142)
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint UP-TO-DATE
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugShaders UP-TO-DATE
:CordovaLib:compileDebugShaders UP-TO-DATE
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
:CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug UP-TO-DATE
:CordovaLib:bundleDebug UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseShaders UP-TO-DATE
:CordovaLib:compileReleaseShaders UP-TO-DATE
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:compileReleaseRenderscript UP-TO-DATE
:CordovaLib:generateReleaseResValues UP-TO-DATE
:CordovaLib:generateReleaseResources UP-TO-DATE
:CordovaLib:packageReleaseResources UP-TO-DATE
:CordovaLib:processReleaseManifest UP-TO-DATE
:CordovaLib:generateReleaseBuildConfig UP-TO-DATE
:CordovaLib:processReleaseResources UP-TO-DATE
:CordovaLib:generateReleaseSources UP-TO-DATE
:CordovaLib:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:CordovaLib:compileReleaseJavaWithJavac UP-TO-DATE
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:CordovaLib:mergeReleaseJniLibFolders UP-TO-DATE
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:CordovaLib:bundleRelease UP-TO-DATE
:prepareAndroidxArchCoreCoreRuntime200Library
:prepareAndroidxAsynclayoutinflaterAsynclayoutinflater100Library
:prepareAndroidxCoordinatorlayoutCoordinatorlayout100Library
:prepareAndroidxCoreCore100Library
:prepareAndroidxCursoradapterCursoradapter100Library
:prepareAndroidxCustomviewCustomview100Library
:prepareAndroidxDocumentfileDocumentfile100Library
:prepareAndroidxDrawerlayoutDrawerlayout100Library
:prepareAndroidxFragmentFragment100Library
:prepareAndroidxInterpolatorInterpolator100Library
:prepareAndroidxLegacyLegacySupportCoreUi100Library
:prepareAndroidxLegacyLegacySupportCoreUtils100Library
:prepareAndroidxLifecycleLifecycleLivedata200Library
:prepareAndroidxLifecycleLifecycleLivedataCore200Library
:prepareAndroidxLifecycleLifecycleRuntime200Library
:prepareAndroidxLifecycleLifecycleViewmodel200Library
:prepareAndroidxLoaderLoader100Library
:prepareAndroidxLocalbroadcastmanagerLocalbroadcastmanager100Library
:prepareAndroidxPrintPrint100Library
:prepareAndroidxSlidingpanelayoutSlidingpanelayout100Library
:prepareAndroidxSwiperefreshlayoutSwiperefreshlayout100Library
:prepareAndroidxVersionedparcelableVersionedparcelable100Library
:prepareAndroidxViewpagerViewpager100Library
:prepareComGoogleAndroidGmsPlayServicesAdsIdentifier1700Library
:prepareComGoogleAndroidGmsPlayServicesBase1700Library
:prepareComGoogleAndroidGmsPlayServicesBasement1700Library
:prepareComGoogleAndroidGmsPlayServicesMeasurement1700Library
:prepareComGoogleAndroidGmsPlayServicesMeasurementApi1700Library
:prepareComGoogleAndroidGmsPlayServicesMeasurementBase1700Library
:prepareComGoogleAndroidGmsPlayServicesMeasurementImpl1700Library
:prepareComGoogleAndroidGmsPlayServicesMeasurementSdk1700Library
:prepareComGoogleAndroidGmsPlayServicesMeasurementSdkApi1700Library
:prepareComGoogleAndroidGmsPlayServicesStats1700Library
:prepareComGoogleAndroidGmsPlayServicesTasks1700Library
:prepareComGoogleFirebaseFirebaseAnalytics1700Library
:prepareComGoogleFirebaseFirebaseCommon1800Library
:prepareComGoogleFirebaseFirebaseCore1700Library
:prepareComGoogleFirebaseFirebaseIid1900Library
:prepareComGoogleFirebaseFirebaseIidInterop1700Library
:prepareComGoogleFirebaseFirebaseMeasurementConnector1800Library
:prepareComGoogleFirebaseFirebaseMessaging1900Library
:prepareOrgApacheCordovaCordovaLib630DebugLibrary UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:processDebugGoogleServices
Parsing json file: D:\cordova\fdk_storyway_app_fran\platforms\android\google-services.json
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResourcesD:\cordova\fdk_storyway_app_fran\platforms\android\build\intermediates\manifests\full\debug\AndroidManifest.xml:26: AAPT: No resource identifier found for attribute 'appComponentFactory' in package 'android'
     FAILED
D:\cordova\fdk_storyway_app_fran\platforms\android\build\intermediates\manifests\full\debug\AndroidManifest.xml:26: error: No resource identifier found for attribute 'appComponentFactory' in package 'android'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

BUILD FAILED

Total time: 56.955 secs
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
(node:12368) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
D:\cordova\fdk_storyway_app_fran\platforms\android\build\intermediates\manifests\full\debug\AndroidManifest.xml:26: AAPT: No resource identifier found for attribute 'appComponentFactory' in package 'android'

D:\cordova\fdk_storyway_app_fran\platforms\android\build\intermediates\manifests\full\debug\AndroidManifest.xml:26: error: No resource identifier found for attribute 'appComponentFactory' in package 'android'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (D:\cordova\fdk_storyway_app_fran\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
(node:12368) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12368) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
----------------------------------------------------------------------------------------------
Somebody please help me!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by csaurav** [comment]
Fixed it by using this https://forum.ionicframework.com/t/firebase-app-unable-to-compile-on-android-with-aapt-error/166564/8

Go over the entire discussion.

**Comment by natsu90** [comment]
i'm using different library instead;
`cordova plugin remove cordova-plugin-fcm`
`cordova plugin add https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated`

sauce: https://stackoverflow.com/a/57086836/1109004
